# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_pos', models.CharField(max_length=200)),
                ('entry_date', models.DateTimeField()),
                ('institution_type', models.CharField(max_length=200)),
                ('institution_name', models.CharField(max_length=200)),
                ('user_type', models.CharField(max_length=100)),
            ],
        ),
    ]
